/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`src/form.test.ts TAP constructor > must match snapshot 1`] = `
Object {
  "id": 0,
  "index": Object {
    "0": Object {
      "children": Object {
        "array": Object {
          "children": Array [
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "6",
              "parent_id": "5",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": "foo",
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "7",
              "parent_id": "5",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": "bar",
            },
          ],
          "dirty": false,
          "errors": Array [],
          "id": "5",
          "parent_id": "0",
          "touched": false,
          "type": "array",
          "validable": true,
        },
        "nested": Object {
          "children": Array [
            Object {
              "children": Object {
                "bar": Object {
                  "children": Array [
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "11",
                      "parent_id": "10",
                      "touched": false,
                      "type": "simple",
                      "validable": true,
                      "value": 1,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "12",
                      "parent_id": "10",
                      "touched": false,
                      "type": "simple",
                      "validable": true,
                      "value": 2,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "13",
                      "parent_id": "10",
                      "touched": false,
                      "type": "simple",
                      "validable": true,
                      "value": 3,
                    },
                  ],
                  "dirty": false,
                  "errors": Array [],
                  "id": "10",
                  "parent_id": "9",
                  "touched": false,
                  "type": "array",
                  "validable": true,
                },
                "foo": Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "14",
                  "parent_id": "9",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": "foobar",
                },
              },
              "dirty": false,
              "errors": Array [],
              "id": "9",
              "parent_id": "8",
              "touched": false,
              "type": "object",
              "validable": true,
            },
            Object {
              "children": Object {
                "bar": Object {
                  "children": Array [
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "17",
                      "parent_id": "16",
                      "touched": false,
                      "type": "simple",
                      "validable": true,
                      "value": 4,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "18",
                      "parent_id": "16",
                      "touched": false,
                      "type": "simple",
                      "validable": true,
                      "value": 8,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "19",
                      "parent_id": "16",
                      "touched": false,
                      "type": "simple",
                      "validable": true,
                      "value": 15,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "20",
                      "parent_id": "16",
                      "touched": false,
                      "type": "simple",
                      "validable": true,
                      "value": 16,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "21",
                      "parent_id": "16",
                      "touched": false,
                      "type": "simple",
                      "validable": true,
                      "value": 23,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "22",
                      "parent_id": "16",
                      "touched": false,
                      "type": "simple",
                      "validable": true,
                      "value": 42,
                    },
                  ],
                  "dirty": false,
                  "errors": Array [],
                  "id": "16",
                  "parent_id": "15",
                  "touched": false,
                  "type": "array",
                  "validable": true,
                },
                "foo": Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "23",
                  "parent_id": "15",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": "boofar",
                },
              },
              "dirty": false,
              "errors": Array [],
              "id": "15",
              "parent_id": "8",
              "touched": false,
              "type": "object",
              "validable": true,
            },
          ],
          "dirty": false,
          "errors": Array [],
          "id": "8",
          "parent_id": "0",
          "touched": false,
          "type": "array",
          "validable": true,
        },
        "object": Object {
          "children": Object {
            "bar": Object {
              "dirty": false,
              "errors": Array [],
              "id": "4",
              "parent_id": "2",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": true,
            },
            "foo": Object {
              "dirty": false,
              "errors": Array [],
              "id": "3",
              "parent_id": "2",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": "foo",
            },
          },
          "dirty": false,
          "errors": Array [],
          "id": "2",
          "parent_id": "0",
          "touched": false,
          "type": "object",
          "validable": true,
        },
        "simple": Object {
          "dirty": false,
          "errors": Array [],
          "id": "1",
          "parent_id": "0",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": 1,
        },
      },
      "dirty": false,
      "errors": Array [],
      "id": "0",
      "parent_id": undefined,
      "touched": false,
      "type": "object",
      "validable": true,
      "validate": undefined,
    },
    "1": Object {
      "dirty": false,
      "errors": Array [],
      "id": "1",
      "parent_id": "0",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": 1,
    },
    "10": Object {
      "children": Array [
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "11",
          "parent_id": "10",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": 1,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "12",
          "parent_id": "10",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": 2,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "13",
          "parent_id": "10",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": 3,
        },
      ],
      "dirty": false,
      "errors": Array [],
      "id": "10",
      "parent_id": "9",
      "touched": false,
      "type": "array",
      "validable": true,
    },
    "11": Object {
      "dirty": false,
      "errors": Array [],
      "id": "11",
      "parent_id": "10",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": 1,
    },
    "12": Object {
      "dirty": false,
      "errors": Array [],
      "id": "12",
      "parent_id": "10",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": 2,
    },
    "13": Object {
      "dirty": false,
      "errors": Array [],
      "id": "13",
      "parent_id": "10",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": 3,
    },
    "14": Object {
      "dirty": false,
      "errors": Array [],
      "id": "14",
      "parent_id": "9",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": "foobar",
    },
    "15": Object {
      "children": Object {
        "bar": Object {
          "children": Array [
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "17",
              "parent_id": "16",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": 4,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "18",
              "parent_id": "16",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": 8,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "19",
              "parent_id": "16",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": 15,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "20",
              "parent_id": "16",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": 16,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "21",
              "parent_id": "16",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": 23,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "22",
              "parent_id": "16",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": 42,
            },
          ],
          "dirty": false,
          "errors": Array [],
          "id": "16",
          "parent_id": "15",
          "touched": false,
          "type": "array",
          "validable": true,
        },
        "foo": Object {
          "dirty": false,
          "errors": Array [],
          "id": "23",
          "parent_id": "15",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": "boofar",
        },
      },
      "dirty": false,
      "errors": Array [],
      "id": "15",
      "parent_id": "8",
      "touched": false,
      "type": "object",
      "validable": true,
    },
    "16": Object {
      "children": Array [
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "17",
          "parent_id": "16",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": 4,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "18",
          "parent_id": "16",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": 8,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "19",
          "parent_id": "16",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": 15,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "20",
          "parent_id": "16",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": 16,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "21",
          "parent_id": "16",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": 23,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "22",
          "parent_id": "16",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": 42,
        },
      ],
      "dirty": false,
      "errors": Array [],
      "id": "16",
      "parent_id": "15",
      "touched": false,
      "type": "array",
      "validable": true,
    },
    "17": Object {
      "dirty": false,
      "errors": Array [],
      "id": "17",
      "parent_id": "16",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": 4,
    },
    "18": Object {
      "dirty": false,
      "errors": Array [],
      "id": "18",
      "parent_id": "16",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": 8,
    },
    "19": Object {
      "dirty": false,
      "errors": Array [],
      "id": "19",
      "parent_id": "16",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": 15,
    },
    "2": Object {
      "children": Object {
        "bar": Object {
          "dirty": false,
          "errors": Array [],
          "id": "4",
          "parent_id": "2",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": true,
        },
        "foo": Object {
          "dirty": false,
          "errors": Array [],
          "id": "3",
          "parent_id": "2",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": "foo",
        },
      },
      "dirty": false,
      "errors": Array [],
      "id": "2",
      "parent_id": "0",
      "touched": false,
      "type": "object",
      "validable": true,
    },
    "20": Object {
      "dirty": false,
      "errors": Array [],
      "id": "20",
      "parent_id": "16",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": 16,
    },
    "21": Object {
      "dirty": false,
      "errors": Array [],
      "id": "21",
      "parent_id": "16",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": 23,
    },
    "22": Object {
      "dirty": false,
      "errors": Array [],
      "id": "22",
      "parent_id": "16",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": 42,
    },
    "23": Object {
      "dirty": false,
      "errors": Array [],
      "id": "23",
      "parent_id": "15",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": "boofar",
    },
    "3": Object {
      "dirty": false,
      "errors": Array [],
      "id": "3",
      "parent_id": "2",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": "foo",
    },
    "4": Object {
      "dirty": false,
      "errors": Array [],
      "id": "4",
      "parent_id": "2",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": true,
    },
    "5": Object {
      "children": Array [
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "6",
          "parent_id": "5",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": "foo",
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "7",
          "parent_id": "5",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": "bar",
        },
      ],
      "dirty": false,
      "errors": Array [],
      "id": "5",
      "parent_id": "0",
      "touched": false,
      "type": "array",
      "validable": true,
    },
    "6": Object {
      "dirty": false,
      "errors": Array [],
      "id": "6",
      "parent_id": "5",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": "foo",
    },
    "7": Object {
      "dirty": false,
      "errors": Array [],
      "id": "7",
      "parent_id": "5",
      "touched": false,
      "type": "simple",
      "validable": true,
      "value": "bar",
    },
    "8": Object {
      "children": Array [
        Object {
          "children": Object {
            "bar": Object {
              "children": Array [
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "11",
                  "parent_id": "10",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": 1,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "12",
                  "parent_id": "10",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": 2,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "13",
                  "parent_id": "10",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": 3,
                },
              ],
              "dirty": false,
              "errors": Array [],
              "id": "10",
              "parent_id": "9",
              "touched": false,
              "type": "array",
              "validable": true,
            },
            "foo": Object {
              "dirty": false,
              "errors": Array [],
              "id": "14",
              "parent_id": "9",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": "foobar",
            },
          },
          "dirty": false,
          "errors": Array [],
          "id": "9",
          "parent_id": "8",
          "touched": false,
          "type": "object",
          "validable": true,
        },
        Object {
          "children": Object {
            "bar": Object {
              "children": Array [
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "17",
                  "parent_id": "16",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": 4,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "18",
                  "parent_id": "16",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": 8,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "19",
                  "parent_id": "16",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": 15,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "20",
                  "parent_id": "16",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": 16,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "21",
                  "parent_id": "16",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": 23,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "22",
                  "parent_id": "16",
                  "touched": false,
                  "type": "simple",
                  "validable": true,
                  "value": 42,
                },
              ],
              "dirty": false,
              "errors": Array [],
              "id": "16",
              "parent_id": "15",
              "touched": false,
              "type": "array",
              "validable": true,
            },
            "foo": Object {
              "dirty": false,
              "errors": Array [],
              "id": "23",
              "parent_id": "15",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": "boofar",
            },
          },
          "dirty": false,
          "errors": Array [],
          "id": "15",
          "parent_id": "8",
          "touched": false,
          "type": "object",
          "validable": true,
        },
      ],
      "dirty": false,
      "errors": Array [],
      "id": "8",
      "parent_id": "0",
      "touched": false,
      "type": "array",
      "validable": true,
    },
    "9": Object {
      "children": Object {
        "bar": Object {
          "children": Array [
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "11",
              "parent_id": "10",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": 1,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "12",
              "parent_id": "10",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": 2,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "13",
              "parent_id": "10",
              "touched": false,
              "type": "simple",
              "validable": true,
              "value": 3,
            },
          ],
          "dirty": false,
          "errors": Array [],
          "id": "10",
          "parent_id": "9",
          "touched": false,
          "type": "array",
          "validable": true,
        },
        "foo": Object {
          "dirty": false,
          "errors": Array [],
          "id": "14",
          "parent_id": "9",
          "touched": false,
          "type": "simple",
          "validable": true,
          "value": "foobar",
        },
      },
      "dirty": false,
      "errors": Array [],
      "id": "9",
      "parent_id": "8",
      "touched": false,
      "type": "object",
      "validable": true,
    },
  },
  "root": Object {
    "children": Object {
      "array": Object {
        "children": Array [
          Object {
            "dirty": false,
            "errors": Array [],
            "id": "6",
            "parent_id": "5",
            "touched": false,
            "type": "simple",
            "validable": true,
            "value": "foo",
          },
          Object {
            "dirty": false,
            "errors": Array [],
            "id": "7",
            "parent_id": "5",
            "touched": false,
            "type": "simple",
            "validable": true,
            "value": "bar",
          },
        ],
        "dirty": false,
        "errors": Array [],
        "id": "5",
        "parent_id": "0",
        "touched": false,
        "type": "array",
        "validable": true,
      },
      "nested": Object {
        "children": Array [
          Object {
            "children": Object {
              "bar": Object {
                "children": Array [
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "11",
                    "parent_id": "10",
                    "touched": false,
                    "type": "simple",
                    "validable": true,
                    "value": 1,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "12",
                    "parent_id": "10",
                    "touched": false,
                    "type": "simple",
                    "validable": true,
                    "value": 2,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "13",
                    "parent_id": "10",
                    "touched": false,
                    "type": "simple",
                    "validable": true,
                    "value": 3,
                  },
                ],
                "dirty": false,
                "errors": Array [],
                "id": "10",
                "parent_id": "9",
                "touched": false,
                "type": "array",
                "validable": true,
              },
              "foo": Object {
                "dirty": false,
                "errors": Array [],
                "id": "14",
                "parent_id": "9",
                "touched": false,
                "type": "simple",
                "validable": true,
                "value": "foobar",
              },
            },
            "dirty": false,
            "errors": Array [],
            "id": "9",
            "parent_id": "8",
            "touched": false,
            "type": "object",
            "validable": true,
          },
          Object {
            "children": Object {
              "bar": Object {
                "children": Array [
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "17",
                    "parent_id": "16",
                    "touched": false,
                    "type": "simple",
                    "validable": true,
                    "value": 4,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "18",
                    "parent_id": "16",
                    "touched": false,
                    "type": "simple",
                    "validable": true,
                    "value": 8,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "19",
                    "parent_id": "16",
                    "touched": false,
                    "type": "simple",
                    "validable": true,
                    "value": 15,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "20",
                    "parent_id": "16",
                    "touched": false,
                    "type": "simple",
                    "validable": true,
                    "value": 16,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "21",
                    "parent_id": "16",
                    "touched": false,
                    "type": "simple",
                    "validable": true,
                    "value": 23,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "22",
                    "parent_id": "16",
                    "touched": false,
                    "type": "simple",
                    "validable": true,
                    "value": 42,
                  },
                ],
                "dirty": false,
                "errors": Array [],
                "id": "16",
                "parent_id": "15",
                "touched": false,
                "type": "array",
                "validable": true,
              },
              "foo": Object {
                "dirty": false,
                "errors": Array [],
                "id": "23",
                "parent_id": "15",
                "touched": false,
                "type": "simple",
                "validable": true,
                "value": "boofar",
              },
            },
            "dirty": false,
            "errors": Array [],
            "id": "15",
            "parent_id": "8",
            "touched": false,
            "type": "object",
            "validable": true,
          },
        ],
        "dirty": false,
        "errors": Array [],
        "id": "8",
        "parent_id": "0",
        "touched": false,
        "type": "array",
        "validable": true,
      },
      "object": Object {
        "children": Object {
          "bar": Object {
            "dirty": false,
            "errors": Array [],
            "id": "4",
            "parent_id": "2",
            "touched": false,
            "type": "simple",
            "validable": true,
            "value": true,
          },
          "foo": Object {
            "dirty": false,
            "errors": Array [],
            "id": "3",
            "parent_id": "2",
            "touched": false,
            "type": "simple",
            "validable": true,
            "value": "foo",
          },
        },
        "dirty": false,
        "errors": Array [],
        "id": "2",
        "parent_id": "0",
        "touched": false,
        "type": "object",
        "validable": true,
      },
      "simple": Object {
        "dirty": false,
        "errors": Array [],
        "id": "1",
        "parent_id": "0",
        "touched": false,
        "type": "simple",
        "validable": true,
        "value": 1,
      },
    },
    "dirty": false,
    "errors": Array [],
    "id": "0",
    "parent_id": undefined,
    "touched": false,
    "type": "object",
    "validable": true,
    "validate": undefined,
  },
}
`
