/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`src/form/form.test.ts TAP constructor > must match snapshot 1`] = `
Object {
  "id": 0,
  "index": Object {
    "0": Object {
      "children": Object {
        "array": Object {
          "children": Array [
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "6",
              "parentId": "5",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": "foo",
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "7",
              "parentId": "5",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": "bar",
            },
          ],
          "dirty": false,
          "errors": Array [],
          "id": "5",
          "parentId": "0",
          "touched": false,
          "type": "array",
          "valid": true,
          "validable": true,
          "value": Array [
            "foo",
            "bar",
          ],
        },
        "nested": Object {
          "children": Array [
            Object {
              "children": Object {
                "bar": Object {
                  "children": Array [
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "11",
                      "parentId": "10",
                      "touched": false,
                      "type": "simple",
                      "valid": true,
                      "validable": true,
                      "value": 1,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "12",
                      "parentId": "10",
                      "touched": false,
                      "type": "simple",
                      "valid": true,
                      "validable": true,
                      "value": 2,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "13",
                      "parentId": "10",
                      "touched": false,
                      "type": "simple",
                      "valid": true,
                      "validable": true,
                      "value": 3,
                    },
                  ],
                  "dirty": false,
                  "errors": Array [],
                  "id": "10",
                  "parentId": "9",
                  "touched": false,
                  "type": "array",
                  "valid": true,
                  "validable": true,
                  "value": Array [
                    1,
                    2,
                    3,
                  ],
                },
                "foo": Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "14",
                  "parentId": "9",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": "foobar",
                },
              },
              "dirty": false,
              "errors": Array [],
              "id": "9",
              "parentId": "8",
              "touched": false,
              "type": "object",
              "valid": true,
              "validable": true,
              "value": Object {
                "bar": Array [
                  1,
                  2,
                  3,
                ],
                "foo": "foobar",
              },
            },
            Object {
              "children": Object {
                "bar": Object {
                  "children": Array [
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "17",
                      "parentId": "16",
                      "touched": false,
                      "type": "simple",
                      "valid": true,
                      "validable": true,
                      "value": 4,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "18",
                      "parentId": "16",
                      "touched": false,
                      "type": "simple",
                      "valid": true,
                      "validable": true,
                      "value": 8,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "19",
                      "parentId": "16",
                      "touched": false,
                      "type": "simple",
                      "valid": true,
                      "validable": true,
                      "value": 15,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "20",
                      "parentId": "16",
                      "touched": false,
                      "type": "simple",
                      "valid": true,
                      "validable": true,
                      "value": 16,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "21",
                      "parentId": "16",
                      "touched": false,
                      "type": "simple",
                      "valid": true,
                      "validable": true,
                      "value": 23,
                    },
                    Object {
                      "dirty": false,
                      "errors": Array [],
                      "id": "22",
                      "parentId": "16",
                      "touched": false,
                      "type": "simple",
                      "valid": true,
                      "validable": true,
                      "value": 42,
                    },
                  ],
                  "dirty": false,
                  "errors": Array [],
                  "id": "16",
                  "parentId": "15",
                  "touched": false,
                  "type": "array",
                  "valid": true,
                  "validable": true,
                  "value": Array [
                    4,
                    8,
                    15,
                    16,
                    23,
                    42,
                  ],
                },
                "foo": Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "23",
                  "parentId": "15",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": "boofar",
                },
              },
              "dirty": false,
              "errors": Array [],
              "id": "15",
              "parentId": "8",
              "touched": false,
              "type": "object",
              "valid": true,
              "validable": true,
              "value": Object {
                "bar": Array [
                  4,
                  8,
                  15,
                  16,
                  23,
                  42,
                ],
                "foo": "boofar",
              },
            },
          ],
          "dirty": false,
          "errors": Array [],
          "id": "8",
          "parentId": "0",
          "touched": false,
          "type": "array",
          "valid": true,
          "validable": true,
          "value": Array [
            Object {
              "bar": Array [
                1,
                2,
                3,
              ],
              "foo": "foobar",
            },
            Object {
              "bar": Array [
                4,
                8,
                15,
                16,
                23,
                42,
              ],
              "foo": "boofar",
            },
          ],
        },
        "object": Object {
          "children": Object {
            "bar": Object {
              "dirty": false,
              "errors": Array [],
              "id": "4",
              "parentId": "2",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": true,
            },
            "foo": Object {
              "dirty": false,
              "errors": Array [],
              "id": "3",
              "parentId": "2",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": "foo",
            },
          },
          "dirty": false,
          "errors": Array [],
          "id": "2",
          "parentId": "0",
          "touched": false,
          "type": "object",
          "valid": true,
          "validable": true,
          "value": Object {
            "bar": true,
            "foo": "foo",
          },
        },
        "simple": Object {
          "dirty": false,
          "errors": Array [],
          "id": "1",
          "parentId": "0",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": 1,
        },
      },
      "dirty": false,
      "errors": Array [],
      "id": "0",
      "parentId": undefined,
      "touched": false,
      "type": "object",
      "valid": true,
      "validable": true,
      "validate": undefined,
      "value": Object {
        "array": Array [
          "foo",
          "bar",
        ],
        "nested": Array [
          Object {
            "bar": Array [
              1,
              2,
              3,
            ],
            "foo": "foobar",
          },
          Object {
            "bar": Array [
              4,
              8,
              15,
              16,
              23,
              42,
            ],
            "foo": "boofar",
          },
        ],
        "object": Object {
          "bar": true,
          "foo": "foo",
        },
        "simple": 1,
      },
    },
    "1": Object {
      "dirty": false,
      "errors": Array [],
      "id": "1",
      "parentId": "0",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": 1,
    },
    "10": Object {
      "children": Array [
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "11",
          "parentId": "10",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": 1,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "12",
          "parentId": "10",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": 2,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "13",
          "parentId": "10",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": 3,
        },
      ],
      "dirty": false,
      "errors": Array [],
      "id": "10",
      "parentId": "9",
      "touched": false,
      "type": "array",
      "valid": true,
      "validable": true,
      "value": Array [
        1,
        2,
        3,
      ],
    },
    "11": Object {
      "dirty": false,
      "errors": Array [],
      "id": "11",
      "parentId": "10",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": 1,
    },
    "12": Object {
      "dirty": false,
      "errors": Array [],
      "id": "12",
      "parentId": "10",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": 2,
    },
    "13": Object {
      "dirty": false,
      "errors": Array [],
      "id": "13",
      "parentId": "10",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": 3,
    },
    "14": Object {
      "dirty": false,
      "errors": Array [],
      "id": "14",
      "parentId": "9",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": "foobar",
    },
    "15": Object {
      "children": Object {
        "bar": Object {
          "children": Array [
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "17",
              "parentId": "16",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": 4,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "18",
              "parentId": "16",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": 8,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "19",
              "parentId": "16",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": 15,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "20",
              "parentId": "16",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": 16,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "21",
              "parentId": "16",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": 23,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "22",
              "parentId": "16",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": 42,
            },
          ],
          "dirty": false,
          "errors": Array [],
          "id": "16",
          "parentId": "15",
          "touched": false,
          "type": "array",
          "valid": true,
          "validable": true,
          "value": Array [
            4,
            8,
            15,
            16,
            23,
            42,
          ],
        },
        "foo": Object {
          "dirty": false,
          "errors": Array [],
          "id": "23",
          "parentId": "15",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": "boofar",
        },
      },
      "dirty": false,
      "errors": Array [],
      "id": "15",
      "parentId": "8",
      "touched": false,
      "type": "object",
      "valid": true,
      "validable": true,
      "value": Object {
        "bar": Array [
          4,
          8,
          15,
          16,
          23,
          42,
        ],
        "foo": "boofar",
      },
    },
    "16": Object {
      "children": Array [
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "17",
          "parentId": "16",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": 4,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "18",
          "parentId": "16",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": 8,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "19",
          "parentId": "16",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": 15,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "20",
          "parentId": "16",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": 16,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "21",
          "parentId": "16",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": 23,
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "22",
          "parentId": "16",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": 42,
        },
      ],
      "dirty": false,
      "errors": Array [],
      "id": "16",
      "parentId": "15",
      "touched": false,
      "type": "array",
      "valid": true,
      "validable": true,
      "value": Array [
        4,
        8,
        15,
        16,
        23,
        42,
      ],
    },
    "17": Object {
      "dirty": false,
      "errors": Array [],
      "id": "17",
      "parentId": "16",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": 4,
    },
    "18": Object {
      "dirty": false,
      "errors": Array [],
      "id": "18",
      "parentId": "16",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": 8,
    },
    "19": Object {
      "dirty": false,
      "errors": Array [],
      "id": "19",
      "parentId": "16",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": 15,
    },
    "2": Object {
      "children": Object {
        "bar": Object {
          "dirty": false,
          "errors": Array [],
          "id": "4",
          "parentId": "2",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": true,
        },
        "foo": Object {
          "dirty": false,
          "errors": Array [],
          "id": "3",
          "parentId": "2",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": "foo",
        },
      },
      "dirty": false,
      "errors": Array [],
      "id": "2",
      "parentId": "0",
      "touched": false,
      "type": "object",
      "valid": true,
      "validable": true,
      "value": Object {
        "bar": true,
        "foo": "foo",
      },
    },
    "20": Object {
      "dirty": false,
      "errors": Array [],
      "id": "20",
      "parentId": "16",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": 16,
    },
    "21": Object {
      "dirty": false,
      "errors": Array [],
      "id": "21",
      "parentId": "16",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": 23,
    },
    "22": Object {
      "dirty": false,
      "errors": Array [],
      "id": "22",
      "parentId": "16",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": 42,
    },
    "23": Object {
      "dirty": false,
      "errors": Array [],
      "id": "23",
      "parentId": "15",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": "boofar",
    },
    "3": Object {
      "dirty": false,
      "errors": Array [],
      "id": "3",
      "parentId": "2",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": "foo",
    },
    "4": Object {
      "dirty": false,
      "errors": Array [],
      "id": "4",
      "parentId": "2",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": true,
    },
    "5": Object {
      "children": Array [
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "6",
          "parentId": "5",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": "foo",
        },
        Object {
          "dirty": false,
          "errors": Array [],
          "id": "7",
          "parentId": "5",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": "bar",
        },
      ],
      "dirty": false,
      "errors": Array [],
      "id": "5",
      "parentId": "0",
      "touched": false,
      "type": "array",
      "valid": true,
      "validable": true,
      "value": Array [
        "foo",
        "bar",
      ],
    },
    "6": Object {
      "dirty": false,
      "errors": Array [],
      "id": "6",
      "parentId": "5",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": "foo",
    },
    "7": Object {
      "dirty": false,
      "errors": Array [],
      "id": "7",
      "parentId": "5",
      "touched": false,
      "type": "simple",
      "valid": true,
      "validable": true,
      "value": "bar",
    },
    "8": Object {
      "children": Array [
        Object {
          "children": Object {
            "bar": Object {
              "children": Array [
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "11",
                  "parentId": "10",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": 1,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "12",
                  "parentId": "10",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": 2,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "13",
                  "parentId": "10",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": 3,
                },
              ],
              "dirty": false,
              "errors": Array [],
              "id": "10",
              "parentId": "9",
              "touched": false,
              "type": "array",
              "valid": true,
              "validable": true,
              "value": Array [
                1,
                2,
                3,
              ],
            },
            "foo": Object {
              "dirty": false,
              "errors": Array [],
              "id": "14",
              "parentId": "9",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": "foobar",
            },
          },
          "dirty": false,
          "errors": Array [],
          "id": "9",
          "parentId": "8",
          "touched": false,
          "type": "object",
          "valid": true,
          "validable": true,
          "value": Object {
            "bar": Array [
              1,
              2,
              3,
            ],
            "foo": "foobar",
          },
        },
        Object {
          "children": Object {
            "bar": Object {
              "children": Array [
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "17",
                  "parentId": "16",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": 4,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "18",
                  "parentId": "16",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": 8,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "19",
                  "parentId": "16",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": 15,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "20",
                  "parentId": "16",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": 16,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "21",
                  "parentId": "16",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": 23,
                },
                Object {
                  "dirty": false,
                  "errors": Array [],
                  "id": "22",
                  "parentId": "16",
                  "touched": false,
                  "type": "simple",
                  "valid": true,
                  "validable": true,
                  "value": 42,
                },
              ],
              "dirty": false,
              "errors": Array [],
              "id": "16",
              "parentId": "15",
              "touched": false,
              "type": "array",
              "valid": true,
              "validable": true,
              "value": Array [
                4,
                8,
                15,
                16,
                23,
                42,
              ],
            },
            "foo": Object {
              "dirty": false,
              "errors": Array [],
              "id": "23",
              "parentId": "15",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": "boofar",
            },
          },
          "dirty": false,
          "errors": Array [],
          "id": "15",
          "parentId": "8",
          "touched": false,
          "type": "object",
          "valid": true,
          "validable": true,
          "value": Object {
            "bar": Array [
              4,
              8,
              15,
              16,
              23,
              42,
            ],
            "foo": "boofar",
          },
        },
      ],
      "dirty": false,
      "errors": Array [],
      "id": "8",
      "parentId": "0",
      "touched": false,
      "type": "array",
      "valid": true,
      "validable": true,
      "value": Array [
        Object {
          "bar": Array [
            1,
            2,
            3,
          ],
          "foo": "foobar",
        },
        Object {
          "bar": Array [
            4,
            8,
            15,
            16,
            23,
            42,
          ],
          "foo": "boofar",
        },
      ],
    },
    "9": Object {
      "children": Object {
        "bar": Object {
          "children": Array [
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "11",
              "parentId": "10",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": 1,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "12",
              "parentId": "10",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": 2,
            },
            Object {
              "dirty": false,
              "errors": Array [],
              "id": "13",
              "parentId": "10",
              "touched": false,
              "type": "simple",
              "valid": true,
              "validable": true,
              "value": 3,
            },
          ],
          "dirty": false,
          "errors": Array [],
          "id": "10",
          "parentId": "9",
          "touched": false,
          "type": "array",
          "valid": true,
          "validable": true,
          "value": Array [
            1,
            2,
            3,
          ],
        },
        "foo": Object {
          "dirty": false,
          "errors": Array [],
          "id": "14",
          "parentId": "9",
          "touched": false,
          "type": "simple",
          "valid": true,
          "validable": true,
          "value": "foobar",
        },
      },
      "dirty": false,
      "errors": Array [],
      "id": "9",
      "parentId": "8",
      "touched": false,
      "type": "object",
      "valid": true,
      "validable": true,
      "value": Object {
        "bar": Array [
          1,
          2,
          3,
        ],
        "foo": "foobar",
      },
    },
  },
  "root": Object {
    "children": Object {
      "array": Object {
        "children": Array [
          Object {
            "dirty": false,
            "errors": Array [],
            "id": "6",
            "parentId": "5",
            "touched": false,
            "type": "simple",
            "valid": true,
            "validable": true,
            "value": "foo",
          },
          Object {
            "dirty": false,
            "errors": Array [],
            "id": "7",
            "parentId": "5",
            "touched": false,
            "type": "simple",
            "valid": true,
            "validable": true,
            "value": "bar",
          },
        ],
        "dirty": false,
        "errors": Array [],
        "id": "5",
        "parentId": "0",
        "touched": false,
        "type": "array",
        "valid": true,
        "validable": true,
        "value": Array [
          "foo",
          "bar",
        ],
      },
      "nested": Object {
        "children": Array [
          Object {
            "children": Object {
              "bar": Object {
                "children": Array [
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "11",
                    "parentId": "10",
                    "touched": false,
                    "type": "simple",
                    "valid": true,
                    "validable": true,
                    "value": 1,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "12",
                    "parentId": "10",
                    "touched": false,
                    "type": "simple",
                    "valid": true,
                    "validable": true,
                    "value": 2,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "13",
                    "parentId": "10",
                    "touched": false,
                    "type": "simple",
                    "valid": true,
                    "validable": true,
                    "value": 3,
                  },
                ],
                "dirty": false,
                "errors": Array [],
                "id": "10",
                "parentId": "9",
                "touched": false,
                "type": "array",
                "valid": true,
                "validable": true,
                "value": Array [
                  1,
                  2,
                  3,
                ],
              },
              "foo": Object {
                "dirty": false,
                "errors": Array [],
                "id": "14",
                "parentId": "9",
                "touched": false,
                "type": "simple",
                "valid": true,
                "validable": true,
                "value": "foobar",
              },
            },
            "dirty": false,
            "errors": Array [],
            "id": "9",
            "parentId": "8",
            "touched": false,
            "type": "object",
            "valid": true,
            "validable": true,
            "value": Object {
              "bar": Array [
                1,
                2,
                3,
              ],
              "foo": "foobar",
            },
          },
          Object {
            "children": Object {
              "bar": Object {
                "children": Array [
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "17",
                    "parentId": "16",
                    "touched": false,
                    "type": "simple",
                    "valid": true,
                    "validable": true,
                    "value": 4,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "18",
                    "parentId": "16",
                    "touched": false,
                    "type": "simple",
                    "valid": true,
                    "validable": true,
                    "value": 8,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "19",
                    "parentId": "16",
                    "touched": false,
                    "type": "simple",
                    "valid": true,
                    "validable": true,
                    "value": 15,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "20",
                    "parentId": "16",
                    "touched": false,
                    "type": "simple",
                    "valid": true,
                    "validable": true,
                    "value": 16,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "21",
                    "parentId": "16",
                    "touched": false,
                    "type": "simple",
                    "valid": true,
                    "validable": true,
                    "value": 23,
                  },
                  Object {
                    "dirty": false,
                    "errors": Array [],
                    "id": "22",
                    "parentId": "16",
                    "touched": false,
                    "type": "simple",
                    "valid": true,
                    "validable": true,
                    "value": 42,
                  },
                ],
                "dirty": false,
                "errors": Array [],
                "id": "16",
                "parentId": "15",
                "touched": false,
                "type": "array",
                "valid": true,
                "validable": true,
                "value": Array [
                  4,
                  8,
                  15,
                  16,
                  23,
                  42,
                ],
              },
              "foo": Object {
                "dirty": false,
                "errors": Array [],
                "id": "23",
                "parentId": "15",
                "touched": false,
                "type": "simple",
                "valid": true,
                "validable": true,
                "value": "boofar",
              },
            },
            "dirty": false,
            "errors": Array [],
            "id": "15",
            "parentId": "8",
            "touched": false,
            "type": "object",
            "valid": true,
            "validable": true,
            "value": Object {
              "bar": Array [
                4,
                8,
                15,
                16,
                23,
                42,
              ],
              "foo": "boofar",
            },
          },
        ],
        "dirty": false,
        "errors": Array [],
        "id": "8",
        "parentId": "0",
        "touched": false,
        "type": "array",
        "valid": true,
        "validable": true,
        "value": Array [
          Object {
            "bar": Array [
              1,
              2,
              3,
            ],
            "foo": "foobar",
          },
          Object {
            "bar": Array [
              4,
              8,
              15,
              16,
              23,
              42,
            ],
            "foo": "boofar",
          },
        ],
      },
      "object": Object {
        "children": Object {
          "bar": Object {
            "dirty": false,
            "errors": Array [],
            "id": "4",
            "parentId": "2",
            "touched": false,
            "type": "simple",
            "valid": true,
            "validable": true,
            "value": true,
          },
          "foo": Object {
            "dirty": false,
            "errors": Array [],
            "id": "3",
            "parentId": "2",
            "touched": false,
            "type": "simple",
            "valid": true,
            "validable": true,
            "value": "foo",
          },
        },
        "dirty": false,
        "errors": Array [],
        "id": "2",
        "parentId": "0",
        "touched": false,
        "type": "object",
        "valid": true,
        "validable": true,
        "value": Object {
          "bar": true,
          "foo": "foo",
        },
      },
      "simple": Object {
        "dirty": false,
        "errors": Array [],
        "id": "1",
        "parentId": "0",
        "touched": false,
        "type": "simple",
        "valid": true,
        "validable": true,
        "value": 1,
      },
    },
    "dirty": false,
    "errors": Array [],
    "id": "0",
    "parentId": undefined,
    "touched": false,
    "type": "object",
    "valid": true,
    "validable": true,
    "validate": undefined,
    "value": Object {
      "array": Array [
        "foo",
        "bar",
      ],
      "nested": Array [
        Object {
          "bar": Array [
            1,
            2,
            3,
          ],
          "foo": "foobar",
        },
        Object {
          "bar": Array [
            4,
            8,
            15,
            16,
            23,
            42,
          ],
          "foo": "boofar",
        },
      ],
      "object": Object {
        "bar": true,
        "foo": "foo",
      },
      "simple": 1,
    },
  },
}
`
